sudo: required
dist: trusty
language: python
python:
  - "2.7"
  # - "3.4" # Note that hyperopt currently seems to have issues with 3.4
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytest h5py flask sklearn networkx
  - source activate test-environment
  - pip install pytest-cov python-coveralls
  - pip install pymongo==2.7.2
  - pip install hyperopt
  - pip install git+git://github.com/Theano/Theano.git
  - pip install keras
  - python setup.py install

# Just run an example for now
script:
  - python $PWD/examples/simple.py
after_success:
  - coveralls
